version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: hr_orbit_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: performance_appraisal
    volumes:
      - db_data_hr_orbit:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7
    container_name: hr_orbit_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend
    image: ${CI_REGISTRY_IMAGE}/backend:latest
    container_name: hr_orbit_backend
    restart: unless-stopped
    volumes:
      # backend expects STATIC_ROOT=/backend/static and MEDIA_ROOT=/backend/media
      - hr_orbit_static_volume:/backend/static
      - hr_orbit_media_volume:/backend/media
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: False
      DB_HOST: db
      DB_NAME: performance_appraisal
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: django-db
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      LOGIN_URL: http://172.17.231.72:3001/login


  frontend:
    build:
      context: ./frontend
    image: ${CI_REGISTRY_IMAGE}/frontend:latest
    container_name: hr_orbit_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    volumes:
      - hr_orbit_static_volume:/static:ro
      - hr_orbit_media_volume:/media:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  celery_worker:
    build:
      context: ./backend
    image: ${CI_REGISTRY_IMAGE}/celery_worker:latest
    container_name: hr_orbit_celery_worker
    restart: unless-stopped
    command: celery -A backend.celery worker --pool=prefork --concurrency=1 --autoscale=2,1 -l info
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: False
      DB_HOST: db
      DB_NAME: performance_appraisal
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: django-db
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      LOGIN_URL: http://172.17.231.72:3001/login
    depends_on:
      - db
      - redis

  celery_beat:
    build:
      context: ./backend
    image: ${CI_REGISTRY_IMAGE}/celery_beat:latest
    container_name: hr_orbit_celery_beat
    restart: unless-stopped
    command: celery -A backend beat -l info
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: False
      DB_HOST: db
      DB_NAME: performance_appraisal
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: django-db
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      LOGIN_URL: http://172.17.231.72:3001/login
    depends_on:
      - db
      - redis

volumes:
  db_data_hr_orbit:
  hr_orbit_static_volume:
  hr_orbit_media_volume:
